# Generated by Django 4.0.6 on 2023-03-24 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='cgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 12, 16, 37, 52624)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='sgst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
