# Generated by Django 4.0.6 on 2023-03-24 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_saleorder_cgst_alter_saleorder_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 12, 21, 51, 746486)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='otherCost',
            field=models.IntegerField(null=True),
        ),
    ]
