# Generated by Django 4.0.6 on 2023-03-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_saleorder_datetime_alter_saleorder_othercost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 13, 28, 28, 806627)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='otherCost',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
