# Generated by Django 4.0.6 on 2023-03-24 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_saleorder_datetime_alter_saleorder_othercost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 13, 32, 5, 944362)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='otherCost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
