# Generated by Django 4.0.6 on 2023-03-24 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_saleorder_datetime_alter_saleorder_othercost'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 14, 34, 23, 103681)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='otherCost',
            field=models.IntegerField(null=True),
        ),
    ]
